###############################################################################
# Copyright (c) 2016-22, Lawrence Livermore National Security, LLC
# and RAJA project contributors. See the RAJA/LICENSE file for details.
#
# SPDX-License-Identifier: (BSD-3-Clause)
###############################################################################

###############################################################################
# General GitLab pipelines configurations for supercomputers and Linux clusters
# at Lawrence Livermore National Laboratory (LLNL).
#
# This entire pipeline is LLNL-specific
# #############################################################################

# We define the following GitLab pipeline variables:
#
# GIT_SUBMODULE_STRATEGY:
# Tells Gitlab to recursively update the submodules when cloning RAJA
#
# ALLOC_NAME:
# On LLNL's ruby, this pipeline creates only one allocation shared among jobs
# in order to save time and resources. This allocation has to be uniquely named
# so that we are sure to retrieve it.
#
# BUILD_ROOT:
# The path to the shared resources between all jobs. The BUILD_ROOT is unique to
# the pipeline, preventing any form of concurrency with other pipelines. This
# also means that the BUILD_ROOT directory will never be cleaned.
#
# DEFAULT_TIME:
# Default time to let the Lassen jobs run will be 30 minutes. However, if it is
# a job that requires more time, it will be overwritten in the lassen template
# file.
# TODO: add a clean-up mechanism

variables:
  MP_BRANCH: "develop"

# Use a service user to run CI. This prevents from running pipelines as an
# actual user.
  LLNL_SERVICE_USER: ""

# Use the service user workspace. Solves permission issues, stores everything
# at the same location whoever triggers a pipeline.
#  CUSTOM_CI_BUILDS_DIR: ""

# Tells Gitlab to recursively update the submodules when cloning the project.
  GIT_SUBMODULE_STRATEGY: recursive

# We build the projects in the CI clone directory.
# TODO: add a clean-up mechanism
  BUILD_ROOT: ${CI_PROJECT_DIR}

# On LLNL's ruby, this pipeline creates only one allocation shared among jobs
# in order to save time and resources. This allocation has to be uniquely named
# so that we are sure to retrieve it and avoid collisions.
  ALLOC_NAME: ${CI_PROJECT_NAME}_ci_${CI_PIPELINE_ID}

# Ruby
# Arguments for top level allocation
  RUBY_BUILD_AND_TEST_SHARED_ALLOC: "--exclusive --partition=pdebug --time=60 --nodes=1"
# Arguments for job level allocation
  RUBY_BUILD_AND_TEST_JOB_ALLOC: "--time=45 --nodes=1"
# Project specific variants for ruby
  PROJECT_RUBY_VARIANTS: "+openmp "
# Project specific deps for ruby
  PROJECT_RUBY_DEPS: ""

# Corona
# Arguments for top level allocation
  CORONA_BUILD_AND_TEST_SHARED_ALLOC: "--time-limit=60m --nodes=1"
# Arguments for job level allocation
  CORONA_BUILD_AND_TEST_JOB_ALLOC: "--time-limit=45m --nodes=1"
# Project specific variants for corona
  PROJECT_CORONA_VARIANTS: "~openmp "
# Project specific deps for corona
  PROJECT_CORONA_DEPS: "^blt@develop "

# Lassen and Butte use a different job scheduler (spectrum lsf) that does not
# allow pre-allocation the same way slurm does.
# Arguments for job level allocation
  LASSEN_BUILD_AND_TEST_JOB_ALLOC: "1 -W 59"
# Project specific variants for lassen
  PROJECT_LASSEN_VARIANTS: "+openmp "
# Project specific deps for lassen
  PROJECT_LASSEN_DEPS: ""

# High level stages
stages:
  - build-and-test
  - multi_project

# Template for jobs triggering a build-and-test sub-pipelines:
.build-and-test:
  stage: build-and-test
  trigger:
    include:
      - local: '.gitlab/custom-jobs.yml'
      - project: 'radiuss/radiuss-shared-ci'
        ref: v2022.09.rc
        file: '${CI_MACHINE}-build-and-test.yml'
      - local: '.gitlab/${CI_MACHINE}-build-and-test-extra.yml'
    strategy: depend
    forward:
      pipeline_variables: true

# If testing develop branch, trigger RAJAPerf pipeline with this version of
# RAJA.
# TODO: Once spack allows to clone a specific commit on demand, then point to the exact commit.
#       This will prevent from sticking to a branch (here develop).
#       MP_BRANCH is short for "Multi-Project Branch" and will usually be develop.
trigger-rajaperf:
  stage: multi_project
  rules:
    - if: '$CI_COMMIT_BRANCH == "${MP_BRANCH}" || $MULTI_PROJECT == "ON"' #run only if ...
  variables:
    UPDATE_RAJA: ${MP_BRANCH}
  trigger:
    project: radiuss/rajaperf
    branch: develop
    strategy: depend

# Import parameters and pipelines defined by the project
include:
  #  - local: .gitlab/custom-variables.yml
  - local: .gitlab/custom-pipelines.yml
